# Generated by Django 5.2.1 on 2025-05-28 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjetoCientifico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao_resumida', models.TextField()),
                ('pais', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('intacto', 'Intacto'), ('avariado', 'Avariado')], max_length=20)),
                ('imagem_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassoDeReparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('concluido', models.BooleanField(default=False)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passos_de_reparo', to='tv.projetocientifico')),
            ],
        ),
    ]
