# Generated by Django 5.2.1 on 2025-05-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PassoDeReparo',
        ),
        migrations.DeleteModel(
            name='ProjetoCientifico',
        ),
    ]
